<?php
// services_feed.php - Reads the XML services feed and displays it
// Demonstrates parsing an XML source (as opposed to querying the DB directly)

$xmlUrl = __DIR__ . '/export_services_xml.php';

// For local same-server generation, capture the XML via output buffering
// rather than an HTTP round-trip, since both files share the same host.
ob_start();
include $xmlUrl;
$xmlString = ob_get_clean();

// The included file sets Content-Type to XML for its own standalone use.
// Reset it here since this page's actual output is HTML.
header('Content-Type: text/html; charset=utf-8');

$services = [];
$loadError = '';

libxml_use_internal_errors(true);
$xml = simplexml_load_string($xmlString);

if ($xml === false) {
    $loadError = 'Failed to parse the XML services feed.';
} else {
    foreach ($xml->service as $serviceNode) {
        $services[] = [
            'id' => (string)$serviceNode['id'],
            'name' => (string)$serviceNode->name,
            'description' => (string)$serviceNode->description,
            'price' => (string)$serviceNode->price,
            'duration_minutes' => (string)$serviceNode->duration_minutes,
        ];
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Our Services - Barbershop & Salon</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: #f4f6f8;
            padding: 40px 20px;
        }
        .container {
            max-width: 900px;
            margin: 0 auto;
        }
        h1 {
            color: #2c3e50;
            margin-bottom: 10px;
        }
        .subtitle {
            color: #888;
            margin-bottom: 30px;
            font-size: 14px;
        }
        .error {
            background: #f8d7da;
            color: #721c24;
            padding: 15px;
            border-radius: 8px;
        }
        .service-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
            gap: 20px;
        }
        .service-card {
            background: white;
            padding: 20px;
            border-radius: 12px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.06);
        }
        .service-card h3 {
            color: #2c3e50;
            margin-bottom: 8px;
        }
        .service-card p.desc {
            color: #666;
            font-size: 14px;
            margin-bottom: 12px;
        }
        .service-card .meta {
            display: flex;
            justify-content: space-between;
            font-size: 14px;
            color: #444;
            border-top: 1px solid #eee;
            padding-top: 10px;
        }
        .service-card .price {
            font-weight: 700;
            color: #667eea;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Our Services</h1>
        <div class="subtitle">Loaded from an XML feed generated by export_services_xml.php</div>

        <?php if ($loadError): ?>
            <div class="error"><?= htmlspecialchars($loadError) ?></div>
        <?php elseif (empty($services)): ?>
            <p>No services found in the feed.</p>
        <?php else: ?>
            <div class="service-grid">
                <?php foreach ($services as $service): ?>
                    <div class="service-card">
                        <h3><?= htmlspecialchars($service['name']) ?></h3>
                        <p class="desc"><?= htmlspecialchars($service['description']) ?></p>
                        <div class="meta">
                            <span>⏱ <?= htmlspecialchars($service['duration_minutes']) ?> min</span>
                            <span class="price">K<?= htmlspecialchars($service['price']) ?></span>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
    </div>
</body>
</html>